openapi: 3.0.0
info:
  title: Update Adoption Status API
  version: 1.0.0
servers:
  - url: http://localhost:3014
paths:
  /adoption/status/{petId}:
    put:
      summary: Update adoption status by petId
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [not_adopted, reserved, adopted]
                notes:
                  type: string
      responses:
        '200':
          description: Status updated
        '404':
          description: Pet not found
